services:
  - type: web
    name: easymart
    env: python
    rootDir: easymart
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn easymart.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
